[game_config]
word_count = 100 # How many words to be proposed in the game
min_word_length = 25 # Minimum length of words
max_word_length = 1000 # Maximum length of words
capitalized_words_count = 1 # If int, count of words of word_count to have capitalized letter in it. If float, percentage of words of word_count to have capitalized letter in it
capitalized_letters_count_perc = 0.5 # If int, numbers of letters in each word to be capitalized. If float, percentage of letters in each word to be capitalized. if 'first', capitalizes only the first letter of the words to be capitalized.
punctuation_word_count_perc = 1 # Same as above, int for count, float for percentage. 
force_shift = 0 # Force to type the right shift of the keyboard
hard_mode = -1 # For hard mode, less common and longer words like 'hydrocharitaceous' are proposed. -1 is for top 10.000 most used 
train_letters = 0 
train_letters_easy_mode = 0 # true for this will proposed most optimal words to type fast and beat records
