[game_config]
word_count = 25 # How many words to be proposed in the game
word_length_min = 4 # Minimum length of words
word_length_max = 1000 # Maximum length of words
capitalized_words = 0 # If int, count of words of word_count to have capitalized letter in it. If float, percentage of words of word_count to have capitalized letter in it
capitalized_letters = 0 # If int, numbers of letters in each word to be capitalized. If float, percentage of letters in each word to be capitalized. if 'first', capitalizes only the first letter of the words to be capitalized.
punctuation = 0 # Same as above, int for count, float for percentage. 
punctuation_char = 0 # number of different punctuations used 
force_shift = 0 # Force to type the right shift of the keyboard
difficulty = 'Medium' # For hard mode, less common and longer words like 'hydrocharitaceous' are proposed. -1 is for top 10.000 most used 
n_games_banned_words = 100 # Wont propose words that have been used if not all have been used. If all have been, will remove the half of the corpus from the last games. in the future, -1 will propose the past game words but I'm kinda lazy to build that up for now so you're gonna have to wait. If you don't like to wait because you're probably a lazy person (no judgement, I'm lazy too) you can go to my website: marclamy.com/gallery and check out my photos. You can also make a PR.
train = true 
train_easy = false # true for this will proposed most optimal words to type fast and beat records
player_name = 'marc'