# Changing this file may cause the game to crash. If you want to change the settings, use the user_default.timl file
[rules] # change it for 'rules'
mode = 'train'
random_definition = false
word_count = 15 # How many words to be proposed in the game
word_length_min = 4 # Minimum length of words
word_length_max = 10 # Maximum length of words
capitalized_words = 0 # If int, count of words of word_count to have  capitalized letter in it. If float, percentage of words of word_count to have capitalized letter in it
capitalized_letters = 'first' # If int, numbers of letters in each word to be capitalized. If float, percentage of letters in each word to be capitalized. if 'first', capitalizes only the first letter of the words to be capitalized.
punctuation = 0 # Same as above, int for count, float for percentage. 
punctuation_char = 1000 # default 1 - number of different punctuations used. depends on the punctuation parameter, if 0 won't be active. if string then it's the char you want
force_shift = 0 # Force to type the right shift of the keyboard
difficulty = 'nltk' # For hard mode, less common and longer words like 'hydrocharitaceous' are proposed. -1 is for top 10.000 most used. the condition is not equal but in so you can list multiple difficulties.
n_games_banned_words = 20 # Wont propose words that have been used if not all have been used. If all have been, will remove the half of the corpus from the last games. in the future, -1 will propose the past game words but I'm kinda lazy to build that up for now so you're gonna have to wait. If you don't like to wait because you're probably a lazy person (no judgement, I'm lazy too) you can go to my website: marclamy.com/gallery and check out my photos. You can also make a PR.
train = false 
train_letter_type = 'lower_case_letter'
train_character_in_focus = 'i'
max_key_count_to_use = 500 
train_n_letters = 5
min_key_count_to_use = 0
train_easy = false # true for this will proposed most optimal words to type fast and beat records
player_name = 'NPC'



[display] #change it for 'display' during the game
display_chart = false 
display_wpm = false
display_words_left = true
display_word_count = -1 # -1 for auto, it's find the width of window and scale accordingly. 
display_character_in_focus = true